name = "TrackingAPI"
uuid = "bcf306fc-d39d-4f25-b732-26abcc96baf2"
authors = ["Jose Esparza <joseesparzadc@icloud.com>"]
version = "0.0.1"

[deps]
Bcrypt = "137488db-d2e6-4fb9-97f3-1e40a263e83c"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSONWebTokens = "9b8beb19-0777-58c6-920b-28f749fee4d3"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
Oxygen = "df9a0d86-3283-4920-82dc-4555fc0d1d8b"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"

[compat]
Bcrypt = "0.1.1"
Compat = "v4.16.0"
HTTP = "1.10.15"
JSON = "0.21.4"
JSONWebTokens = "1.1.1"
Memoize = "0.4.4"
Oxygen = "1.7.1"
SQLite = "1.6.1"
julia = "1.0"

[extras]
Bcrypt = "137488db-d2e6-4fb9-97f3-1e40a263e83c"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
Mocking = "78c3b35d-d492-501b-9361-3d52fe80e533"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Compat", "HTTP", "JSON", "Memoize", "Mocking", "SQLite", "Test"]
